---
name: 'Format, lint, typecheck, test, build'

on:
  pull_request:
    branches: [main]
jobs:
  ci:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./package.json
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: pnpm install
      - name: Format
        run: pnpm run format
      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: pnpm run build
